In [1]:
import numpy as np

def create_adjacency_matrix(num_nodes, connections):
    """创建邻接矩阵"""
    adj_matrix = np.zeros((num_nodes, num_nodes))
    for conn in connections:
        # 假设conn是一个元组 (from_node, to_node, value)
        from_node, to_node, value = conn
        adj_matrix[from_node][to_node] = value
        adj_matrix[to_node][from_node] = value  # 假设是无向图
    return adj_matrix

def create_system_of_equations(adj_matrix):
    """根据邻接矩阵创建方程组"""
    num_nodes = adj_matrix.shape[0]
    A = np.zeros((num_nodes - 1, num_nodes - 1))  # 不包括一个参考节点
    B = np.zeros(num_nodes - 1)
    
    for i in range(num_nodes - 1):
        for j in range(num_nodes):
            if i != j:  # 跳过选定的参考节点
                A[i][j - 1 if j < i + 1 else j - 2] = adj_matrix[i][j]
                B[i] -= adj_matrix[i][j] * 0  # 参考节点流入量设为0

    return A, B

# 定义管网
num_nodes = 4  # 节点数量
connections = [
    (0, 1, 10),
    (0, 2, 5),
    (1, 2, 2),
    (1, 3, 1),
    (2, 3, 15)
]

# 创建邻接矩阵
adj_matrix = create_adjacency_matrix(num_nodes, connections)
print("邻接矩阵:")
print(adj_matrix)

# 创建方程组
A, B = create_system_of_equations(adj_matrix)
print("方程组 A:")
print(A)
print("方程组 B:")
print(B)

# 求解方程组
flow_rates = np.linalg.solve(A, B)
print("节点流量分布:")
print(flow_rates)


邻接矩阵:
[[ 0. 10.  5.  0.]
 [10.  0.  2.  1.]
 [ 5.  2.  0. 15.]
 [ 0.  1. 15.  0.]]
方程组 A:
[[ 5.  0. 10.]
 [ 2.  1. 10.]
 [ 2. 15.  5.]]
方程组 B:
[0. 0. 0.]
节点流量分布:
[0. 0. 0.]
