In [8]:
import numpy as np

def construct_equations(adjacency_matrix):
    num_nodes = len(adjacency_matrix)
    # 初始化方程系数矩阵和常数项向量
    A = np.zeros((num_nodes, num_nodes))
    b = np.zeros(num_nodes)

    for i in range(num_nodes):
        for j in range(num_nodes):
            if adjacency_matrix[i][j]!= 0:
                A[i][i] += adjacency_matrix[i][j]
                A[i][j] = -adjacency_matrix[i][j]
        # 根据流入等于流出（基尔霍夫第一定律）设置常数项
        b[i] = sum(adjacency_matrix[i])

    return A, b

# 示例邻接矩阵表示管网连接情况，正数表示流出节点的流量，负数表示流入节点的流量
adj_matrix = np.array([
    [1, 22, 12],
    [24, 20, 6],
    [21, 1, 4]
])

A, b = construct_equations(adj_matrix)

print("系数矩阵 A：")
print(A)
print("常数项向量 b：")
print(b)

# 求解方程
flows = np.linalg.solve(A, b)
print("节点流量：")
print(flows)

系数矩阵 A：
[[ 33. -22. -12.]
 [-24. -14.  -6.]
 [-21.  -1.  -4.]]
常数项向量 b：
[35. 50. 26.]
节点流量：
[-0.70591017 -1.3035461  -2.46808511]
